### ISSUE TITLE
[Question] is there a way to upload the data downloaded back to github to recreate repo, issues and PRs? 

### ISSUE THREAD

**Issue by Vikas-kum** [josegonzalez/python-github-backup#154]

**Comment by josegonzalez** [comment]
No, the github api doesn't support that.

Maybe you can recreate it if you have a Github Enterprise account, but otherwise you'd have to recomment everything as a bot user of some sort.

As this project is for generating backups, I encourage you to create another project that can interpret the backups and upload them in a desired format.
