### ISSUE TITLE
Add support for fine-grained tokens

### ISSUE THREAD

**Issue by dceuinton** [josegonzalez/python-github-backup#205]
GitHub are allowing fine grained tokens and it seems like tokens with read-only access to the repositories that need to be backed up would be amazing for this project. However, I couldn't get them to work and had to use the "Classic" tokens.

![image](https://user-images.githubusercontent.com/32469210/204422593-b7e2d994-f115-4f01-8bc5-162ffcf172b2.png)

**Comment by mprofitlich** [comment]
Thank you for your code addition. I am using your fork for backing with the -all option.

I propose to add a check of all needed rights at the beginning before starting the copy process. Otherwise, if a needed right is not given, errors occur only when the particular copy job starts (in my case copying hooks).

**Comment by Ondkloss** [comment]
This should be resolved in 0.44.0 / 0.44.1 with the merge of PR #216.
